=== ZeusWPI/hydra/server/tests/schema_resto_sandwiches.json
{
  "$id": "https://hydra.ugent.be/schema/resto/sandwiches",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Sandwiches",
  "description": "Structure of the sandwich file. Note: this is not API documentation; do not rely on it.",
  "type": "array",
  "items": {
    "type": "object",
    "description": "A sandwich.",
    "required": [
      "name",
      "ingredients",
      "price_medium",
      "price_small"
    ],
    "properties": {
      "name": {
        "type": "string",
        "description": "The name of the sandwich.",
        "examples": ["Brie"]
      },
      "ingredients": {
        "type": "array",
        "description": "A list of the ingredients in the sandwich.",
        "items": {
          "type": "string"
        },
        "examples": [[
          "ham",
          "asperge",
          "sla"
        ]]
      },
      "price_medium": {
        "type": "string",
        "description": "The (textual) price in euros for a normal sandwich.",
        "examples": ["2.70"]
      },
      "price_small": {
        "type": "string",
        "description": "The (textual) price in euros for a small sandwich.",
        "examples": ["1.60"]
      }
    }
  }
}

=== ZeusWPI/hydra/scraper/resto/1.0/sandwiches.json
[
  {
    "name": "Kruidenkaas",
    "ingredients": [
      "kruidenkaas",
      "tomaat",
      "sla",
      "komkommer",
      "ei"
    ],
    "price_small": "1.30",
    "price_medium": "1.90"
  },
  {
    "name": "Kaas",
    "ingredients": [
      "kaas",
      "tomaat",
      "sla",
      "komkommer",
      "ei",
      "mayonaise"
    ],
    "price_small": "1.30",
    "price_medium": "2.00"
  },
  {
    "name": "Kip curry",
    "ingredients": [
      "kip curry",
      "tomaat",
      "sla",
      "komkommer",
      "ei"
    ],
    "price_small": "1.40",
    "price_medium": "2.00"
  },
  {
    "name": "Kip curry hawaï",
    "ingredients": [
      "kip curry",
      "sla",
      "komkommer",
      "ei",
      "ananas"
    ],
    "price_small": "1.40",
    "price_medium": "2.00"
  },
  {
    "name": "Préparé",
    "ingredients": [
      "préparé",
      "tomaat",
      "sla",
      "komkommer",
      "ei"
    ],
    "price_small": "1.40",
    "price_medium": "2.00"
  },
  {
    "name": "Martino",
    "ingredients": [
      "préparé",
      "tomaat",
      "augurk",
      "mosterd",
      "tabasco"
    ],
    "price_small": "1.40",
    "price_medium": "2.10"
  },
  {
    "name": "Ham",
    "ingredients": [
      "ham",
      "tomaat",
      "sla",
      "komkommer",
      "ei",
      "mayonaise"
    ],
    "price_small": "1.40",
    "price_medium": "2.10"
  },
  {
    "name": "Brie",
    "ingredients": [
      "brie",
      "sla",
      "honing",
      "pijnboompitten"
    ],
    "price_small": "1.40",
    "price_medium": "2.30"
  },
  {
    "name": "Gerookte zalm - kruidenkaas",
    "ingredients": [
      "gerookte zalm",
      "kruidenkaas",
      "ui"
    ],
    "price_small": "1.40",
    "price_medium": "2.30"
  },
  {
    "name": "Tropical",
    "ingredients": [
      "ham",
      "kaas",
      "sla",
      "komkommer",
      "ei",
      "ananas",
      "cocktailsaus"
    ],
    "price_small": "1.50",
    "price_medium": "2.20"
  },
  {
    "name": "Maison",
    "ingredients": [
      "ham",
      "kaas",
      "tomaat",
      "sla",
      "ei",
      "augurk",
      "mayonaise",
      "cocktailsaus"
    ],
    "price_small": "1.40",
    "price_medium": "2.20"
  },
  {
    "name": "Boulet Bicky",
    "ingredients": [
      "gevogelte boulet",
      "geroosterde ui",
      "Bicky-dressing",
      "augurk"
    ],
    "price_small": "1.50",
    "price_medium": "2.30"
  },
  {
    "name": "Kabeljauwsalade",
    "ingredients": [
      "kabeljauwsalade",
      "tomaat",
      "sla",
      "komkommer",
      "ei"
    ],
    "price_small": "1.50",
    "price_medium": "2.30"
  },
  {
    "name": "Ecologisch",
    "ingredients": [
      "wisselend broodbeleg",
      "sla"
    ],
    "price_small": "1.50",
    "price_medium": "2.40"
  },
  {
    "name": "Tomaat-mozzarella",
    "ingredients": [
      "mozarella",
      "tomaat",
      "sla",
      "groene pesto met basilicum"
    ],
    "price_small": "1.50",
    "price_medium": "2.40"
  },
  {
    "name": "Hoeve-broodje",
    "ingredients": [
      "geitenkaas",
      "gebakken spek",
      "appeltjes",
      "sla"
    ],
    "price_small": "1.60",
    "price_medium": "2.40"
  }
]
